export const SHOW_CREATE_PROXY = 'SHOW_CREATE_PROXY';
export const SHOW_PROXY_COPY = 'SHOW_PROXY_COPY';
export const SHOW_PROXY_DETAIL = 'SHOW_PROXY_DETAIL';
export const HIDE_PROXY_DETAIL = 'HIDE_PROXY_DETAIL';

export const SHOW_CREATE_PATTERN = 'SHOW_CREATE_PATTERN';
export const SHOW_PATTERN_DETAIL = 'SHOW_PATTERN_DETAIL';
export const HIDE_PATTERN_DETAIL = 'HIDE_PATTERN_DETAIL';

export const SHOW_REQUEST_DETAIL = 'SHOW_REQUEST_DETAIL';
export const HIDE_REQUEST_DETAIL = 'HIDE_REQUEST_DETAIL';
